"""add worktag

Revision ID: 4ef9efb7a432
Revises: 612110229216
Create Date: 2017-08-26 19:40:05.793676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef9efb7a432'
down_revision = '612110229216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('event_endtime', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('worktag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'worktag')
    op.drop_column('posts', 'event_endtime')
    # ### end Alembic commands ###
