"""add worktype

Revision ID: 612110229216
Revises: 8f00bb8e65ca
Create Date: 2017-08-26 15:17:43.057604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612110229216'
down_revision = '8f00bb8e65ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('event_starttime', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('worktype', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'worktype')
    op.drop_column('posts', 'event_starttime')
    # ### end Alembic commands ###
