"""initial migration

Revision ID: 8e7214598a3d
Revises: 
Create Date: 2017-06-23 11:05:41.364443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7214598a3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prd_type', sa.Text(), nullable=True),
    sa.Column('inserttime', sa.DateTime(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('filetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    # ### end Alembic commands ###
