"""empty message

Revision ID: e44c3e07e2e9
Revises: 
Create Date: 2017-06-07 17:05:52.819154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44c3e07e2e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('inserttime', sa.DateTime(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('filetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    # ### end Alembic commands ###
