"""empty message

Revision ID: f64006708455
Revises: 00eb656b206b
Create Date: 2017-12-20 15:14:51.412441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64006708455'
down_revision = '00eb656b206b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('stat', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'stat')
    # ### end Alembic commands ###
