"""initial migration

Revision ID: a8d253809a21
Revises: 
Create Date: 2017-06-06 08:26:33.794798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d253809a21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prd_type', sa.Text(), nullable=True),
    sa.Column('inserttime', sa.DateTime(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('filetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inserttime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    # ### end Alembic commands ###
